image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80


ingress:
  path: /api/provide-in-pipeline
  
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"


serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  
imagePullSecrets:
  - name: regcred