image:
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80


ingress:
  path: /api/provide-in-pipeline
  domainName1: "kubernetes.haidinger.me"
  domainName2: "k8s.haidinger.me"
resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  
imagePullSecrets:
  - name: regcred