image:
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false

ingress:
  path: /api/provide-in-pipeline
  affinity: false
  
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"


serviceAccount:
  create: false
  annotations: {}
  name: ""
  
autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  vpa:
    enabled: false
  
imagePullSecrets:
  - name: regcred