apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "Kubernetes.Api.Chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "*.haidinger.me"
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "Kubernetes.Api.Chart.fullname" . }}
            port:
              name: http
