{{- if .Values.autoscaling.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "Kubernetes.Api.Chart.fullname" . }}
  labels:
    {{- include "Kubernetes.Api.Chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "Kubernetes.Api.Chart.fullname" . }}
  updatePolicy:
    updateMode: "Auto"
{{- end }}
