name: Publish Docker image to GitHub Container Registry

on:
  push:
    branches: [ main ]

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.5.0 # version of HEL to install
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/api-chart

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: install helm
      uses: azure/setup-helm@v1
      with:
        version: ${{ env.HELM_VERSION_TO_INSTALL }}

    - name: login to acr using helm
      run: |
        echo ${{ secrets.ACTION_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

    - name: save helm chart to local registry
      run: |
        helm chart save ${{ github.workspace }} ${{ env.GCR_IMAGE }}:${{ github.sha }}

    - name: publish chart to acr
      run: |
        helm chart push ${{ env.GCR_IMAGE }}:${{ github.sha }}

