name: Publish Docker image to GitHub Container Registry

on:
  push:
    branches: [ main ]

env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
  HELM_VERSION_TO_INSTALL: 3.5.0 # version of HEL to install
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/api-chart
  CHART_VERSION: 1.0.0
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.ACTION_TOKEN }}
      id: install

    - name: login to acr using helm
      run: |
        echo ${{ secrets.ACTION_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

    - name: Save and push Helm chart to GitHub Container Registry
      run: |
        helm package ${{ github.workspace }}/api-chart --destination ./
        helm push ./${{ github.repository_owner }}-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/api-chart:${{ github.sha }}
        helm push ./${{ github.repository_owner }}-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/api-chart:latest

